app/admin/routes/index.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user


import json

from ..forms.login import LoginForm


module = Blueprint('admin', __name__)

_name_ = 'Flask Admin'



@module.route('/admin', methods=['GET'])
def index():
    if current_user.is_authenticated:
        return render_template('admin/index.html')
    return redirect(url_for('login_manager.login'))

templates/splash/index.html
{% extends "splash/forms/base.html" %}
{{ super() }}



{% block body_content %}
<div id="top_container_row" class="top_container row">
    <div class="col">
        <div class="d-flex justify-content-center">
            <img src="{{ url_for('static', filename='viuhka/media/logo.png') }}">
            <h1>Työllisyysviuhka</h1>
        </div>
        <div class="d-flex justify-content-center">
            <p class="logo-smalltext">Työllistymistä edistäviä palveluja Turun alueella</p>
        </div>
    </div>
</div>
<div class="wip row">
    <div class="col">
        <p>Verkkosivustoamme kehitetään.<br />
        Sivuston toiminnassa ja sisällössä esiintyy tämän vuoksi puutteita.<br />
        Puutteet korjataan vaiheittain vuoden 2020 aikana.</p>
    </div>
</div>
<div id="main_container_row" class="row">
    <div class="sidebar col-md-4">
        <div class="row">
            <div class="col-12">
                <div class="d-flex justify-content-center">
                    <div class="column-title">
                        Valinnat
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <input class="form-control" id="serviceSearch" placeholder="Haku">
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col accordion-container">
                <div class="accordion" id="accordion">
                    {% for category in categories %}
                    {% if category.amount() >= 1 %}
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title-text">
                                <div class="d-flex justify-content-left font-weight-bold">
                                    <a id="cg_{{ category.category.sanitized() }}" data-toggle="collapse"
                                         href="#{{ category.category.sanitized() }}"
                                         categoryId="{{ category.id }}">
                                        {{ category.category.name }}
                                    </a>
                                </div>
                            </h4>
                        </div>
                        <div class="card-content collapse" id="{{ category.category.sanitized() }}" data-parent="#accordion">
                            <ul class="list-group list-group-flush">
                                {% for category_item in category.items %}
                                {% if category_item.has_service() %}
                                <li class="list-group-item service">
                                    <a href="javascript:void(0);" id="cgItem_{{ category_item.id }}"
                                        sanitized="{{ category_item.sanitized() }}" cgItemCategoryId="{{ category.id }}">
                                        {{ category_item.text }}
                                    </a>
                                </li>
                                {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="main-content col">
        <div class="row">
            <div class="col">
                <div class="d-flex justify-content-center title-container">
                    <h2>
                        Palvelut
                    </h2>
                </div>
                <div id="searchSpinner">
                    <i class="fa fa-refresh ld ld-spin"></i>
                </div>
                <div id="resultSet">
                    <div class="results-row">
                        <p id="results"></p>
                    </div>
                    <div class="resetFilters-row">
                        <a id="resetFilters" href="javascript:void(0);">
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col table-container">
                        <table class="table table-condensed row" id="serviceTable">
                            <tbody>
                                {% for service in services %}
                                {% if service.published %}
                                <tr>
                                    <td id="row_{{ service.id }}" class="{{ service.joined_sanitized() }}">
                                        <div class="row">
                                            <div class="col">
                                                <div class="d-flex justify-content-center">
                                                    <div class="col">
                                                        <a href="{{ url_for('index.details', id=service.id) }}">
                                                            <h2>{{ service.name }}</h2>
                                                        </a>
                                                        <p>{{ service.organization }}</p>
                                                        <p>{{ service.ingress }}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row information">
    <div class="col">
        <div class="d-flex justify-content-center">
            <a href='#'>Ilmoita virheestä</a>
        </div>
    </div>
    <div class="col">
        <div class="d-flex justify-content-center">
            {% if current_user.is_staff() %}
            <a href="{{ url_for('admin.index') }}">Muokkaa palvelun tietoja</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}
{% block scripts %}
<script type="text/javascript">var total = "{{ total }}"; </script>
<script type="text/javascript" src={{ url_for('static', filename='viuhka/scripts/templates/splash/index.js') }}></script>
{% endblock scripts %}