app/admin/forms/account.py
from wtforms_alchemy                            import ModelForm
from wtforms                                    import SelectField, IntegerField
from flask_wtf                                  import FlaskForm

from app.utils.models.account                   import Account
from app.utils.models.rank                      import ranks

class AccountForm(ModelForm, FlaskForm):
    id                      =   IntegerField('Id')
    rank                    =   SelectField('Rank', choices=tuple([(k, ranks[k]) for k in ranks]))

    class Meta:
        model = Account

app/admin/forms/login.py
from flask_wtf                              import FlaskForm
from wtforms.validators                     import length, DataRequired
from wtforms                                import StringField, PasswordField


class LoginForm(FlaskForm):
    username = StringField('Username', [DataRequired(), length(max=32)])
    password = PasswordField('Password', [DataRequired(), length(max=100)])

app/admin/forms/register.py
from flask_wtf                          import FlaskForm
from wtforms.validators                 import length, DataRequired
from wtforms                            import StringField, PasswordField


class RegisterForm(FlaskForm):
    username        = StringField('Username', [DataRequired(), length(max=32)])
    email           = StringField('Email', [DataRequired(), length(max=100)])
    password        = PasswordField('Password', [DataRequired(), length(max=100)])

app/services/forms/category.py
from wtforms_alchemy                            import ModelForm, QuerySelectMultipleField
from wtforms                                    import StringField, SelectMultipleField, IntegerField
from flask_wtf                                  import FlaskForm

from app.services.models.category               import Category
from app.services.models.category_items         import CategoryItems


class CategoryForm(ModelForm, FlaskForm):
    id                  = IntegerField()
    category_items      = SelectMultipleField('Category Items', choices=[])

    class Meta:
        model = Category
    

app/admin/routes/login.py
from flask                              import Blueprint, render_template, request, redirect, url_for
from flask_login                        import current_user, logout_user, login_user
from flask_wtf.csrf                     import validate_csrf

from app.managers.password              import generate_hash_pass

from app.utils.models                   import Account
from app.utils.extensions.database      import module as connector

from app.admin.forms.login              import LoginForm
from app.admin.forms.register           import RegisterForm

import json

module = Blueprint('login_manager', __name__)

_name_ = 'Admin Login'


@module.route('/admin/login', methods=['POST', 'GET'])
def admin_login():
    if request.method == 'POST':
        form = LoginForm(request.form)
        validate_csrf(form.csrf_token)
        account = Account.query.filter_by(username=form.username.data, password=generate_hash_pass(form.username.data, form.password.data)).first()
        if account:
            if login_user(account):
                account.set_status(online=True).save()
                return redirect(url_for('admin.index'), code=302)
        return json.dumps({
                'success': False
            }), 401, {'ContentType':'application/json'}
    else:
        if current_user.is_authenticated and current_user.is_staff():
            return redirect(url_for('admin.index'), code=302)
        return render_template('admin/pages/login.html', form=LoginForm())


@module.route('/admin/logout', methods=['GET', 'POST'])
def admin_logout():
    if not current_user.is_authenticated:
        return redirect(url_for('login_manager.admin_login'))
    current_user.online = 0
    current_user.save()
    logout_user()
    return redirect(url_for('admin.index'))


@module.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        form = LoginForm(request.form)
        account = Account.query.filter_by(username=form.username.data, password=generate_hash_pass(form.username.data, form.password.data)).first()
        if account:
            if login_user(account):
                account.set_status(online=True).save()
                return redirect(url_for('index.index'), code=302)
        return json.dumps({
                'success': False
            }), 400, {'ContentType':'application/json'}
    else:
        if current_user.is_authenticated and current_user.is_staff():
            return redirect(url_for('index.index'))
        return render_template('splash/actions/login.html', form=LoginForm())


@module.route('/logout', methods=['GET', 'POST'])
def logout():
    if not current_user.is_authenticated:
        return redirect(url_for('login_manager.login'))
    current_user.online = 0
    current_user.save()
    logout_user()
    return redirect(url_for('index.index'))


@module.route('/register', methods=['GET', 'POST'])
def register():
    callback =  {
                    'success': True,
                    'form': '',
                    'errors': []
                }
    if current_user.is_authenticated:
        logout_user()                   # How did this happen..?
        return redirect('register')

    if request.method == 'POST':
        form = RegisterForm(request.form)
        username = form.username.data
        email = form.email.data

        if not username:
            callback['success'] = False
            callback['form'] = 'username'
            callback['errors'].append('Invalid username')
            return json.dumps(callback), 400, {'ContentType':'application/json'} 
        if not email:
            callback['success'] = False
            callback['form'] = 'email'
            callback['errors'].append('Invalid email')
            return json.dumps(callback), 400, {'ContentType':'application/json'} 



        account = Account.query.filter_by(email=email).first()
        if account:
            callback['success'] = False
            callback['form'] = 'email'
            callback['errors'].append('Email already registered')
            return json.dumps(callback), 400, {'ContentType':'application/json'} 


        account = Account.query.filter_by(username=form.username.data).first()
        if account:
            callback['success'] = False
            callback['form'] = 'username'
            callback['errors'].append('Username already registered')
            return json.dumps(callback), 400, {'ContentType':'application/json'} 



        password = generate_hash_pass(username, form.password.data)
        account = Account(
            username = username,
            password = password,
            email = email
        )
        account = account.save()
        account.change_rank(
            level=1
        )
        account = Account.query.filter_by(username=username, password=password, email=email).first()
        if account:
            return json.dumps(callback), 200, {'ContentType':'application/json'}
        return json.dumps(
            {
                'success': False
            }), 401, {'ContentType':'application/json'}
    else:
        return render_template('splash/actions/register.html')

app/index/routes.py
from flask                              import Blueprint, render_template, send_from_directory, request, redirect, url_for, abort
from app.utils                          import paginate, paginate_id
from app.services.models.category       import sequalized_categories
from app.services.models.service        import Service, services_from_category, find_service, amount, get_services
from app.services.models.category_items import get_category_item_by_name
from app.services.forms.service         import ServiceForm
from flask_login                        import login_required
from wtforms.fields.simple              import TextAreaField
from flask_wtf.csrf                     import validate_csrf

import json

module = Blueprint('index', __name__)

_name_ = 'Splash'


@module.route('/')
def index():
    _type = request.args.get('type')
    if _type is None or _type is not 'show':
        return render_template('splash/index.html', categories=sequalized_categories(), services=services_from_category(), total=amount())
    else:
        id = request.json.get('categoryname')
        return render_template('splash/index.html', categories=sequalized_categories(), services=services_from_category(id), total=amount())

@module.route('/info')
def info():  
    return render_template('splash/forms/info.html')

@module.route('/saavutettavuus')
def saavutettavuus():  
    return render_template('splash/forms/saavutettavuus.html')

@module.route('/provider_info')
def provider_info():  
    return render_template('splash/forms/provider_info.html')

@module.route('/service')
def service():
    return redirect(url_for('index.index'))

    
@module.route('/form', methods=['GET', 'POST'])
@login_required
def form():  
    return render_template('splash/forms/form.html', form=ServiceForm()) 

@module.route('/search', methods=['GET'])
def search():
    return redirect(url_for('index.index'))

@module.route('/details/<id>')
def details(id):
    if id:
        service = find_service(id)
        if service:
            return render_template('splash/actions/services/view.html', service=service)
    abort(404)

"""
                                                            <h2>{{ service.name }}</h2>
                                                        </a>
                                                        <p>{{ service.organization }}</p>
                                                        <p>{{ service.ingress }}</p>
"""


@module.route('/get_service', methods=['GET'])
def get_service():
    ret = {'data': []}
    search = request.args.get('service')
    for service in get_services():
        if search.lower() in service.name.lower() or search.lower() in service.organization.lower() or search.lower() in service.ingress.lower():
            ret['data'].append(
                    {
                        'name': str(service.name),
                        'organization': str(service.organization),
                        'ingress': str(service.ingress),
                        'url': str(url_for('index.details', id=service.id)),
                        'id': int(service.id),
                        'sanitized': str(service.joined_sanitized())
                    }
            )
    return json.dumps({
        'status': True,
        **ret,
        'length': len(ret)
    }), 200, {'ContentType':'application/json'}

@module.route('/edit/<id>', methods=['GET','POST'])
def edit(id):
    if request.method == 'GET':
        if id:
            service = find_service(id)
            if service:
                form = ServiceForm()
                for ff in form.__dict__:
                    for sf in service.__dict__:
                        if ff == sf:
                            if isinstance(form.__dict__[ff], TextAreaField):
                                form.__dict__[ff].process_data(service.__dict__[sf])
                return render_template('splash/actions/services/edit.html', service=service, form=form)
        return abort(404)
    else:
        form = ServiceForm(request.form)
        service = find_service(id)
        owner = service.owner_id

        category_items = service.category_items

        validate_csrf(form.csrf_token.data)

        service.__init__(
            **form.data
        )
        service.category_items = category_items
        service.owner_id = owner
        service.save()
        if find_service(id):
            return json.dumps({
                'success':True
            }), 200, {'ContentType':'application/json'}
        return abort(400)
    
@module.route('/contact')
def contact():  
    return render_template('splash/forms/contact.html')

app/services/routes/service.py
from flask                              import Blueprint, render_template, request, redirect, Response, url_for
from flask_login                        import login_required, current_user
from flask_wtf.csrf                     import validate_csrf

from app.services.models.service        import ( Service, get_services, find_service, 
                                        amount, create_new, paginate_service_owner_id )
from app.services.forms.service         import ServiceForm
from app.services.models.category       import get_category, sequalized_categories

from app.utils                          import root, join, exit, paginate

from wtforms.fields.simple              import TextAreaField

import json
import pickle

module = Blueprint('service', __name__)

_name_ = 'Services'


@module.route('/service/list', methods=['GET'])
def list_service():
    page = request.args.get('page', 1, int)
    if current_user.rank().level < 2:
        services = paginate_service_owner_id(current_user.id, page=page, per_page=25)
    else:
        services = paginate(Service.query, page=page, per_page=25)
    return render_template('splash/actions/services/list.html', services=services, amount=amount, current_page=page)


@module.route('/admin/service', methods=['GET', 'POST'])
@login_required
def service():
    _type = str(request.args.get('type'))
    id = request.args.get('id') 
    if _type == 'edit':
        if request.method == 'GET':
            if id == 0:
                return redirect(url_for('service.services'))
            service = find_service(id)
            if service:
                form = ServiceForm()
                try:    
                    form.category_items.process_data([v for v in service.category_items.values()])
                except:
                    form.category_items.process_data([] if service.category_items is None else service.category_items)

                for ff in form.__dict__:
                    for sf in service.__dict__:
                        if ff == sf:
                            if isinstance(form.__dict__[ff], TextAreaField):
                                form.__dict__[ff].process_data(service.__dict__[sf])
                try:
                    if service.start:          form.start.data = str(service.start).replace(' ','T')
                    if service.end:            form.end.data = str(service.end).replace(' ','T')
                except:
                    pass
                return render_template('admin/pages/services/_edit.html', service=service, form=form, categories=sequalized_categories)
            return render_template('admin/pages/404.html', reason='Service', content='Not found')
        else:
            form = ServiceForm(request.form)
            service = find_service(id)
            owner = service.owner_id # cache

            if form.start.data is None and service.start is not None:
                form.start.data = service.start
            if form.end.data is None and service.end is not None:
                form.end.data = service.end


            service.__init__(**form.data)
            service.owner_id = owner
            validate_csrf(service.csrf_token)
            service.save()
            try:
                if find_service(service.id):
                    return json.dumps({
                            'success': True
                        }), 200, {'ContentType':'application/json'}
            except:
                pass
            return json.dumps({
                    'success': False
                }), 400, {'ContentType':'application/json'}
            
    elif _type == 'add':
        form = ServiceForm(request.form)
        service = Service(
            **form.data
        )
        if current_user.rank().level < 1:
            service.owner_id = current_user.id
        validate_csrf(service.csrf_token)
        try: service.category_items = dict(enumerate(service.category_items))
        except: pass
        service.save()
        try:
            if find_service(service.id):
                return json.dumps({
                        'success': True,
                        'service_id': str(service.id)
                    }), 200, {"ContentType":"Application/Json"}
        except:
            pass
        return json.dumps({
            'success':False,
        }), 400, {'ContentType':'application/json'}
    elif _type == 'new':
        if request.method == 'GET':
            return render_template('admin/pages/services/_new.html', form=ServiceForm(), categories=sequalized_categories)
        return redirect(url_for('service.services'))
    elif _type == 'delete':
        if id == 0:
            return redirect(url_for('service.services'))
        service = find_service(id)
        if service:
            service.delete()
    return redirect(url_for('service.services'))

@module.route('/admin/services', methods=['GET'])
@login_required
def services():
    page = request.args.get('page', 1, int)
    if current_user.rank().level < 2:
        services = paginate_service_owner_id(current_user.id,  page=page, per_page=25)
    else:
        services = paginate(Service.query,  page=page, per_page=25)
    return render_template('admin/pages/services/services.html', 
                        services=services, amount=amount)

templates/splash/forms/401.html
{% extends "splash/forms/base.html" %}
{{ super() }}

{% block body_content %}
<center>
    <h1>Kirjautuminen ei onnistunut</h1>
    <p>
        Väärä käyttäjä tai salasana.
    </p>
</center>
{% endblock %}

templates/splash/forms/base.html
<!DOCTYPE html>
<html lang="en">
{% block head %}
<head>
    {% block meta_head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% endblock %}
    <title>Työllistymistä edistävät palvelut {% block title %}{% endblock %}</title>
    <!-- Fav Icon -->
    <link href="{{ url_for('static', filename='viuhka/media/favicon.ico') }}" rel="shortcut icon" />
    <!-- Load css -->
    <link href="{{ url_for('static', filename='viuhka/styles/shepherd-theme-arrows.css') }}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='viuhka/styles/bootstrap4/css/bootstrap.min.css') }}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='viuhka/styles/starter-template.css') }}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='css/index.scss.css')}}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='viuhka/styles/employment.css') }}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='vendor/loading.io/loading.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
</head>
{% endblock %}
{% block body %}
<body>
    <!-- navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="{{ FORCE_SCRIPT_NAME }}/">Työllisyysviuhka</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false"
                aria-label="Toggle naviation">
                <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <div class="nav-container w-100">
                <ul class="nav navbar-nav mr-autso navbar-let psx-2 nav-fill">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('service.list_service') }}">Lista palveluista</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('index.provider_info') }}">Lisää palvelu</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('index.info') }}">Tietoa käyttäjälle</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('index.contact') }}">Tietoa palvelutuottajalle</a>
                    </li>
                    {% if current_user.is_authenticated %}
                        <li class="nav-item" style="float:right;">
                            <a class="nav-link" href="{{ url_for('login_manager.logout') }}?next={{ request.path }}">{{ current_user.username }} (Kirjaudu ulos)</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('login_manager.login') }}?next={{ request.path }}">Kirjaudu sisään(palveluntuottaja)</a>
                        </li>
                </ul>
                {% endif %}
                </div>
            </div>
    </nav>

    <!-- ./navbar -->
    <main class="container">
    {% block body_content %}
    {% endblock %}
    </main>
    {% block footer %}
    <!-- Footer -->
    {% block footer_context %}
    {% endblock %}
    <footer class="container-fluid">
        <div class="main-footer row">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-3">
                        <div class="row">
                            <div class="col footer-brand">
                                <b>Työllisyysviuhka</b>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <br>
                                <img src="{{ url_for('static', filename='viuhka/media/turkulogo.svg') }}" height="72">
                                <br>
                                &nbsp;
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-9">
                        <div class="footer-links">
                            <ul>
                                <li><a href="{{ url_for('index.info') }}">Tietoa sivustosta</a></li>
                                <li><a href="https://www.turku.fi/tietosuoja">Rekisteriseloste</a></li>
                                <li><a href="https://www.turku.fi/tietosuoja">Tietosuoja</a></li>
                                <li><a href="{{ url_for('index.saavutettavuus') }}">Saavutettavuus</a></li>
                                <li><a href="mailto:viuhka@turku.fi">Palaute</a></li>
                                <li><a href="http://data.turku.fi/">Avoin data</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="container">
                <img width="100%" src="{{ url_for('static', filename='viuhka/media/alalogot.png') }}">
            </div>
        </div>
    </footer>
    <!-- ./footer -->
    {% endblock %}




    <!-- Load scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="{{ url_for('static',filename='viuhka/styles/bootstrap4/js/bootstrap.min.js') }}"></script>
    <script src="https://pagination.js.org/dist/2.1.4/pagination.min.js"></script>
    <script src="{{ url_for('static', filename='viuhka/scripts/tether.js') }}"></script>
    <script src="{{ url_for('static', filename='viuhka/scripts/shepherd.js') }}"></script>
    <script src="{{ url_for('static', filename='viuhka/scripts/tether.min.js') }}"></script>
    <script src="{{ url_for('static', filename='viuhka/scripts/ie10-viewport-bug-workaround.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    {% block scripts %}
    {% endblock %}

    <script type="text/javascript">
    var _paq = _paq || [];
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
        var u = "//wwwstats2.turku.fi/piwik/";
        _paq.push(['setTrackerUrl', u+'piwik.php']);
        _paq.push(['setSideId', 19]);
        var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
        g.type = 'text/javascript'; g.async = true; g.defer = true; g.src = u + 'piwik.js'; s.parentNode.insertBefore(g,s);
    })();
    </script>
    <noscript><p><img src="//wwwstats2.turku.fi/piwik/piwik.php?idside=19" style="border:0;" alt="" /></p></noscript>
</body>
{% endblock %}
</html>

templates/splash/forms/contact.html
{% extends 'splash/forms/base.html' %}
{{ super() }}

{% block body_content %}
<h1>Yhteystiedot</h1>
<p>Työllisyysviuhkan avulla voit etsiä työttömälle työnhakijalle tarkoitettuja palveluita yhdestä paikasta.
    Olemme keränneet palveluita Turun alueen palvelutuottajilta kuten Turun kaupungilta, TE-toimistolta sekä
    kolmannen sektorin toimijoilta.
</p>
<p>Työllisyysviuhkaa kehitetään parhaillaan ja olemme kiitollisia kaikesta saamastamme palautteesta, sekä
    kehitysideoista, joilla voimme tehdä viuhkasta entistä paremmin palvelevan. Yhteyttä voit ottaa meihin alla
    olevan sähköpostiosoitteen kautta.
</p>
<p>
    Ota myös <a href="mailto:viuhka@turku.fi">yhteyttä</a> mikäli haluat päästä lisäämään palvelusi osaksi
    Työllisyysviuhkaa.</a>
</p>
<form method="get" action="{{ url_for('index.index') }}">
    <button type="submit" class="button-info-viuhka button-info">Sulje ohje</button>
</form>
{% endblock %}

templates/splash/forms/info.html
{% extends "splash/forms/base.html" %}

{% block body_content %}
<div class="row">
    <div class="col">
        <h1>Tietoa palvelusta</h1>
    <div class=page-text-left>
        <p>
        Työllisyysviuhkan avulla voit etsiä työttömälle työnhakijalle tarkoitettuja palveluita yhdestä paikasta.
        Olemme keränneet palveluita Turun alueen palvelutuottajilta kuten Turun kaupungilta, TE-toimistolta sekä
        kolmannen sektorin toimijoilta. Palvelujen kerääminen jatkuu edelleen ja olemme erityisesti nyt kehitysvaiheessa
        kiitollisia kaikesta palautteestanne.
        </p>
    </div>
    <form method="get" action="{{ url_for('index.index') }}">
        <button type="submit" class="button-info-viuhka button-info">Sulje ohje</button>
    </form>
    </div>
</div>

{% endblock %}

templates/splash/forms/provider_info.html
{% extends "splash/forms/base.html" %}
{{ super() }}


{% block body_content %}
    <h1>Lisää palvelu</h1>
    <div class=page-text-left>
    <p>Seuraavalla sivulla voit lisätä palvelun tiedot Työllisyysviuhkaan</p>
    <form method="get" action="{{ FORCE_SCRIPT_NAME }}/form/">
        <button type="submit" class="button-info-viuhka button-info">Lisää palvelu</button>
    </form>
    </div>
{% endblock %}

templates/splash/forms/saavutettavuus.html
{% extends "splash/forms/base.html" %}

{% block body_content %}

<h1>Saavutettavuusseloste</h1>
<div class=page-text-left>
<p>Työllisyysviuhkan verkkosivustoa koskee laki digitaalisten palvelujen tarjoamisesta (306/2019), joka pohjautuu EU:n saavutettavuusdirektiiviin (2102/2016).
    Lain ja säädöksen mukaan julkishallinnon organisaatioiden verkkopalvelujen (verkkosivustot ja mobiilisovellukset) täytyy olla saavutettavia. Se tarkoittaa, että kuka tahansa voi käyttää palveluja helposti, toimintarajoitteista huolimatta.
        Työllisyysviuhkan verkkosivusto on julkaistu vuonna 2017. Lain mukaan ennen 23.9.2018 julkaistujen verkkosivustojen pitää olla saavutettavuusvaatimusten mukaisia viimeistään 23.9.2020.
            Tavoitteena on, että Työllisyysviuhkan verkkosivusto täyttää saavutettavuuden vaatimukset määräaikaan mennessä.</p>
        <p>Voit lähettää palautetta verkkosivuston saavutettavuudesta ja käytettävyydestä osoitteeseen viuhka@turku.fi.</p>
            <p>Tämä saavutettavuusseloste on laadittu 23.9.2019.</p>
</div>
<form method="get" action="{{ FORCE_SCRIPT_NAME }}/">
    <button type="submit" class="button-info-viuhka button-info">Sulje ohje</button>
</form>
{% endblock %}

templates/splash/forms/thank_you.html
{% extends 'splash/forms/base.html' %}
{{ super() }}

{% block body_content %}
    <h2><label>Kiitos!</label></h2>
    <p>Palvelun tiedot siirtyvät Palveluviuhkan verkkosivuille, kun ylläpitäjä on tarkistanut ja hyväksynyt tiedot.</p>
    <p>Muistathan jatkossa käydä Palveluviuhkan verkkosivuilla päivittämässä palvelun tietoja, jos palvelussa tapahtuu
        muutoksia. Muista myös päivittää verkko-osoitteiden linkit, jos ne muuttuvat.</p>
    <p>Mikäli myöhemmin haluat poistaa palvelun tiedot kokonaan Palveluviuhkan verkkosivuilta, lähetä asiasta
        sähköpostitse viesti suoraan ylläpitäjälle osoitteella viuhka@turku.fi</p>
    <br>
    <form method="get" action="{{ url_for('service.list_service') }}">
    <button type="submit" class="btn button-info">Lista palveluista</button>
</form>
{% endblock %}