app/services/models/category_items.py
from app.utils.extensions.database import module as connector



class CategoryItems(connector.Model):
    __table_args__      = {
                            'extend_existing': True
                        } 


    id          = connector.Column(connector.Integer, primary_key=True)
    category_id = connector.Column(connector.Integer)
    text        = connector.Column(connector.String(100))

    def __str__(self):
        return self.text

    def __init__(self, category_id, text):
        self.category_id = category_id
        self.text = text
    
    def save(self):
        connector.session.add(self)
        connector.session.commit()
        return self

    def delete(self):
        connector.session.delete(self)
        connector.session.commit()

    def sanitized(self):
        return self.text.replace(' ','').replace(',','').replace('-','').lower()

    def has_service(self):
        from app.services.models.service import Service
        from app.utils import sanitize
        services = Service.query.all()
        for service in services:
            if service.category_items:
                for cgItem in service.category_items:
                    if sanitize(cgItem) == self.sanitized():
                        return service.published
        return False


def get_relation_type(category_id):
    query = CategoryItems.query.filter_by(category_id=category_id).all()
    return query if query else []

def amount():
    return len(CategoryItems.query.all())


def get_category_item_by_name(name):
    return CategoryItems.query.filter_by(text=name).first()

app/services/forms/category.py
from wtforms_alchemy                            import ModelForm, QuerySelectMultipleField
from wtforms                                    import StringField, SelectMultipleField, IntegerField
from flask_wtf                                  import FlaskForm

from app.services.models.category               import Category
from app.services.models.category_items         import CategoryItems


class CategoryForm(ModelForm, FlaskForm):
    id                  = IntegerField()
    category_items      = SelectMultipleField('Category Items', choices=[])

    class Meta:
        model = Category
    

app/services/forms/service.py
from wtforms_alchemy                                import ModelForm, QuerySelectMultipleField
from wtforms                                        import SelectMultipleField, IntegerField, BooleanField
from wtforms.fields.html5                           import DateTimeLocalField

from wtforms.validators                             import Required

from flask_wtf                                      import Form

from ..models.service                               import Service

class ServiceForm(ModelForm, Form):
    category_items              =   SelectMultipleField('Category Items', choices=[])
    
    search_result_priority      =   IntegerField(label="Search result priority")
    start                       =   DateTimeLocalField(label="Start", format='%Y-%m-%dT%H:%M', validators=[Required()])
    end                         =   DateTimeLocalField(label="End",   format='%Y-%m-%dT%H:%M', validators=[Required()])
    published                   =   BooleanField(label="Published", default=False)
    open_ended                  =   BooleanField(label="Open ended", default=False)

    class Meta:
        model = Service
        exclude = [
            'category_items'
        ]

app/index/routes.py
from flask                              import Blueprint, render_template, send_from_directory, request, redirect, url_for, abort
from app.utils                          import paginate, paginate_id
from app.services.models.category       import sequalized_categories
from app.services.models.service        import Service, services_from_category, find_service, amount, get_services
from app.services.models.category_items import get_category_item_by_name
from app.services.forms.service         import ServiceForm
from flask_login                        import login_required
from wtforms.fields.simple              import TextAreaField
from flask_wtf.csrf                     import validate_csrf

import json

module = Blueprint('index', __name__)

_name_ = 'Splash'


@module.route('/')
def index():
    _type = request.args.get('type')
    if _type is None or _type is not 'show':
        return render_template('splash/index.html', categories=sequalized_categories(), services=services_from_category(), total=amount())
    else:
        id = request.json.get('categoryname')
        return render_template('splash/index.html', categories=sequalized_categories(), services=services_from_category(id), total=amount())

@module.route('/info')
def info():  
    return render_template('splash/forms/info.html')

@module.route('/saavutettavuus')
def saavutettavuus():  
    return render_template('splash/forms/saavutettavuus.html')

@module.route('/provider_info')
def provider_info():  
    return render_template('splash/forms/provider_info.html')

@module.route('/service')
def service():
    return redirect(url_for('index.index'))

    
@module.route('/form', methods=['GET', 'POST'])
@login_required
def form():  
    return render_template('splash/forms/form.html', form=ServiceForm()) 

@module.route('/search', methods=['GET'])
def search():
    return redirect(url_for('index.index'))

@module.route('/details/<id>')
def details(id):
    if id:
        service = find_service(id)
        if service:
            return render_template('splash/actions/services/view.html', service=service)
    abort(404)

"""
                                                            <h2>{{ service.name }}</h2>
                                                        </a>
                                                        <p>{{ service.organization }}</p>
                                                        <p>{{ service.ingress }}</p>
"""


@module.route('/get_service', methods=['GET'])
def get_service():
    ret = {'data': []}
    search = request.args.get('service')
    for service in get_services():
        if search.lower() in service.name.lower() or search.lower() in service.organization.lower() or search.lower() in service.ingress.lower():
            ret['data'].append(
                    {
                        'name': str(service.name),
                        'organization': str(service.organization),
                        'ingress': str(service.ingress),
                        'url': str(url_for('index.details', id=service.id)),
                        'id': int(service.id),
                        'sanitized': str(service.joined_sanitized())
                    }
            )
    return json.dumps({
        'status': True,
        **ret,
        'length': len(ret)
    }), 200, {'ContentType':'application/json'}

@module.route('/edit/<id>', methods=['GET','POST'])
def edit(id):
    if request.method == 'GET':
        if id:
            service = find_service(id)
            if service:
                form = ServiceForm()
                for ff in form.__dict__:
                    for sf in service.__dict__:
                        if ff == sf:
                            if isinstance(form.__dict__[ff], TextAreaField):
                                form.__dict__[ff].process_data(service.__dict__[sf])
                return render_template('splash/actions/services/edit.html', service=service, form=form)
        return abort(404)
    else:
        form = ServiceForm(request.form)
        service = find_service(id)
        owner = service.owner_id

        category_items = service.category_items

        validate_csrf(form.csrf_token.data)

        service.__init__(
            **form.data
        )
        service.category_items = category_items
        service.owner_id = owner
        service.save()
        if find_service(id):
            return json.dumps({
                'success':True
            }), 200, {'ContentType':'application/json'}
        return abort(400)
    
@module.route('/contact')
def contact():  
    return render_template('splash/forms/contact.html')

app/services/routes/category.py
from flask                                  import Blueprint, render_template, request, redirect, url_for
from flask_login                            import login_required
from flask_wtf.csrf                         import validate_csrf

from app.services.models.category           import sequalized_categories, get_category, get_category_by_name, amount, Category
from app.services.models.category_items     import CategoryItems, get_category_item_by_name
from app.services.forms.category            import CategoryForm

import json


module = Blueprint('category', __name__)

_name_ = 'Categories'

@module.route('/admin/category', methods=['GET', 'POST'])
@login_required
def category():
    _type = request.args.get('type')
    id = request.args.get('id')
    if _type == 'edit':
        if request.method == 'GET':
            category = sequalized_categories(id)
            if category:
                return render_template('admin/pages/categories/_edit.html', category=category, form=CategoryForm())
            return render_template(url_for('category.categories'))
        else:
            form = CategoryForm(request.form)
            cat = get_category(form.id.data)
            del form.id
            category_items = form.category_items.data
            del form.category_items
            if cat:
                cat.__init__(**form.data)
            else:
                cat = Category(**form.data)
            validate_csrf(cat.csrf_token)
            cat.save()
            return json.dumps(
                {
                    'success':True
                }
            ), 200, {'ContentType':'application/json'}
    elif _type == 'new':
        if request.method == 'GET':
            return render_template('admin/pages/categories/_new.html', form=CategoryForm(), render_type='new')
        else:
            form = CategoryForm(request.form)
            del form.id
            category_items = form.category_items.data
            del form.category_items
            cat = Category(
                **form.data
            )
            cat.save()
            for item in category_items:
                cat_items = CategoryItems(
                    category_id=cat.id,
                    text=item
                )
                cat_items.save()
            return json.dumps(
                {
                    'success':True
                }
            ), 200, {'ContentType': 'application/json' }
    elif _type == 'delete':
        category = get_category(id)
        if category:
            category.delete()
    return redirect(url_for('category.categories'))

@module.route('/admin/categories', methods=['GET'])
@login_required
def categories():
    return render_template('admin/pages/categories/categories.html', amount=amount, categories=sequalized_categories, len=len)




@module.route('/admin/category/item', methods=['POST', 'GET'])
@login_required
def category_item():
    _type = request.args.get('type')
    id = request.args.get('id')
    if _type == 'add':
        cat = CategoryItems(
            category_id=id,
            text=request.form.get('text')
        )
        cat.save()
        return json.dumps(
            {
                'success':True
            }
        ), 200, {'ContentType':'application/json'}
    elif _type == 'delete':
        for item in request.form.getlist('categoryItems[]'):
            cat = get_category_item_by_name(item)
            cat.delete()
        return json.dumps(
            {
                'success':True
            }
        ), 200, {'ContentType':'application/json'}
    return render_template(url_for('category.categories'))

app/services/routes/service.py
from flask                              import Blueprint, render_template, request, redirect, Response, url_for
from flask_login                        import login_required, current_user
from flask_wtf.csrf                     import validate_csrf

from app.services.models.service        import ( Service, get_services, find_service, 
                                        amount, create_new, paginate_service_owner_id )
from app.services.forms.service         import ServiceForm
from app.services.models.category       import get_category, sequalized_categories

from app.utils                          import root, join, exit, paginate

from wtforms.fields.simple              import TextAreaField

import json
import pickle

module = Blueprint('service', __name__)

_name_ = 'Services'


@module.route('/service/list', methods=['GET'])
def list_service():
    page = request.args.get('page', 1, int)
    if current_user.rank().level < 2:
        services = paginate_service_owner_id(current_user.id, page=page, per_page=25)
    else:
        services = paginate(Service.query, page=page, per_page=25)
    return render_template('splash/actions/services/list.html', services=services, amount=amount, current_page=page)


@module.route('/admin/service', methods=['GET', 'POST'])
@login_required
def service():
    _type = str(request.args.get('type'))
    id = request.args.get('id') 
    if _type == 'edit':
        if request.method == 'GET':
            if id == 0:
                return redirect(url_for('service.services'))
            service = find_service(id)
            if service:
                form = ServiceForm()
                try:    
                    form.category_items.process_data([v for v in service.category_items.values()])
                except:
                    form.category_items.process_data([] if service.category_items is None else service.category_items)

                for ff in form.__dict__:
                    for sf in service.__dict__:
                        if ff == sf:
                            if isinstance(form.__dict__[ff], TextAreaField):
                                form.__dict__[ff].process_data(service.__dict__[sf])
                try:
                    if service.start:          form.start.data = str(service.start).replace(' ','T')
                    if service.end:            form.end.data = str(service.end).replace(' ','T')
                except:
                    pass
                return render_template('admin/pages/services/_edit.html', service=service, form=form, categories=sequalized_categories)
            return render_template('admin/pages/404.html', reason='Service', content='Not found')
        else:
            form = ServiceForm(request.form)
            service = find_service(id)
            owner = service.owner_id # cache

            if form.start.data is None and service.start is not None:
                form.start.data = service.start
            if form.end.data is None and service.end is not None:
                form.end.data = service.end


            service.__init__(**form.data)
            service.owner_id = owner
            validate_csrf(service.csrf_token)
            service.save()
            try:
                if find_service(service.id):
                    return json.dumps({
                            'success': True
                        }), 200, {'ContentType':'application/json'}
            except:
                pass
            return json.dumps({
                    'success': False
                }), 400, {'ContentType':'application/json'}
            
    elif _type == 'add':
        form = ServiceForm(request.form)
        service = Service(
            **form.data
        )
        if current_user.rank().level < 1:
            service.owner_id = current_user.id
        validate_csrf(service.csrf_token)
        try: service.category_items = dict(enumerate(service.category_items))
        except: pass
        service.save()
        try:
            if find_service(service.id):
                return json.dumps({
                        'success': True,
                        'service_id': str(service.id)
                    }), 200, {"ContentType":"Application/Json"}
        except:
            pass
        return json.dumps({
            'success':False,
        }), 400, {'ContentType':'application/json'}
    elif _type == 'new':
        if request.method == 'GET':
            return render_template('admin/pages/services/_new.html', form=ServiceForm(), categories=sequalized_categories)
        return redirect(url_for('service.services'))
    elif _type == 'delete':
        if id == 0:
            return redirect(url_for('service.services'))
        service = find_service(id)
        if service:
            service.delete()
    return redirect(url_for('service.services'))

@module.route('/admin/services', methods=['GET'])
@login_required
def services():
    page = request.args.get('page', 1, int)
    if current_user.rank().level < 2:
        services = paginate_service_owner_id(current_user.id,  page=page, per_page=25)
    else:
        services = paginate(Service.query,  page=page, per_page=25)
    return render_template('admin/pages/services/services.html', 
                        services=services, amount=amount)

templates/splash/actions/services/edit.html
{% extends 'splash/forms/base.html' %}
{{ super() }}

{% block body_content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="row">
  <a class="btn btn-primary btn-lg" href="javascript:history.back()" role="button"
    style="background: #00A97A;border-color: #00A97A;">
    <i class="fa fa-caret-left"></i>
    <i class="fa fa-caret-left"></i>
    <i class="fa fa-caret-left"></i>
    &nbsp; Palaa hakuun
  </a>
</div>

<div class="container">
<form id="addService" role="form">
  {{ form.csrf_token }}
  <h1>Muokkaa palvelua</h1>
  <h2>Palvelun nimi</h2>
  {{ form.name(id="name", placeholder="Name", class="form-control", value=service.name, required=True) }}
  <h2>Palvelun toteuttaja</h2>
  {{ form.organization(id="organization", placeholder="Organisaatio", class="form-control", value="", required=True) }}
  <h2>Tiivistelmä</h2>
  {{ form.ingress(id="ingress", placeholder="Ingress", class="form-control", value="", required=True) }}
  <h2>Palvelun kuvaus</h2>
  {{ form.description(id="description", placeholder="Description", class="form-control", required=True) }}
  <h2>Toimintaohjeet</h2>
  {{ form.description4(id="description4", placeholder="Toimintaohjeet", class="form-control")  }}
  <h2>Ehdot ja kriteerit</h2>
  {{ form.constraint(id="constraint", placeholder="Ehdot ja kriteerit", class="form-control", value="") }}
  <h2>Käyntitiedot</h2>
  {{ form.address(id="address", placeholder="Katuosoite", class="form-control", value="") }}
  <h2>Osoitteen tarkennus</h2>
  {{ form.address_extended(id="address_extended", placeholder="Osoitteen tarkennus", class="form-control", value="") }}
  <h2>Postiosoite</h2>
  {{ form.post_address(id="post_address", placeholder="Postiosoite", class="form-control", value="") }}
  <h2>Verkkosivu</h2>
  {{ form.www(id="www", placeholder="Verkkosivu", class="form-control", value=service.www) }}
  <h2>Facebook</h2>
  {{ form.facebook(id="facebook", placeholder="Facebook", class="form-control", value=service.facebook) }}
  <h2>Twitter</h2>
  {{ form.twitter(id="twitter", placeholder="Twitter", class="form-control", value=service.twitter) }}
  <button type="submit" class="btn btn-fill btn-primary">Tallenna</button>
</form>
</div>
{% endblock %}



{% block scripts %}
<script>
  $('#addService').on('submit', function (event) {
    console.log('askflagkdsag')
    event.preventDefault();
    var csrf_token = "{{ csrf_token() }}";
    $.ajaxSetup({
      cache: false,
      beforeSend: function (xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrf_token);
        }
      }
    });
    var url = "{{ url_for('index.edit', id=service.id) }}".replace('&amp;', '&');
    $.ajax({
      type: 'POST',
      url: url,
      data: $(this).serialize(),
      success: function () {
        $(location).attr('href', "{{ url_for('index.search') }}")
      }
    });
  });
</script>
{% endblock %}

templates/splash/actions/services/list.html
{% extends 'splash/forms/base.html' %}
{{ super() }}

{% block body_content %}

<div class='center-text2 container'>
  <h1>Lista palveluistasi</h1>
  <div class="row">
    <div class="col">
    <div class="list-text panel panel-default" style="text-align:initial;">
    {% if amount() >= 1 %}
      {% for service in services.items %}
        {% if current_user.rank().level < 2 and service.owner_id == current_user.id %}
        <a href="{{ url_for('index.details', id=service.id) }}">{{ service.name }}</a> &nbsp;
        <a href="{{ url_for('index.edit', id=service.id) }}" style="color:lightgray">muokkaa</a>
        {% else %}
        <a href="{{ url_for('index.details', id=service.id) }}">{{ service.name }}</a> &nbsp;
        <a href="{{ url_for('index.edit', id=service.id) }}" style="color:lightgray">muokkaa</a>
        {% endif %}
        <br>
      {% endfor %}
      <div id="pagination" style="text-align:center;">
        {% for page_num in services.iter_pages() %}
          {% if page_num %}
          <a  href="{{ url_for('service.list_service', page=page_num) }}" 
              class="btn btn-link">{{ page_num }}
          </a>
          {% else %}
          ...
          {% endif %}
        {% endfor %}
        {% if services.pages > 0 %}
          {% if current_page + 1 > services.pages %}
            <a href="{{ url_for('service.list_service', page=current_page - 1) }}" class="btn btn-link">
              <i class="fa fa-chevron-left"></i>
            </a>
          {% else %}
            <a href="{{ url_for('service.list_service', page=current_page + 1) }}" class="btn btn-link">
              <i class="fa fa-chevron-right"></i>
            </a>
          {% endif %}
        {% else %}
          <h1>Et ole vielä lisännyt yhtään palvelua</h1>
          <form method="get" action="{{ url_for('index.form') }}">
        <button type="submit" class="button-info-viuhka button-info">Lisää palvelu</button>
        </form>
        {% endif %}
      </div>
    {% else %}
      <h1>Palveluja ei ole vielä lisätty.</h1>
      <p> Palveluja ei ole vielä lisätty Työllisyysviuhkaan, odotathan.</p>
        <form method="get" action="{{ url_for('index.index') }}">
        <button type="submit" class="button-info-viuhka button-info">Takaisin</button>
        </form>
    </div>
    </div>
  </div>
  
 </div>
    {% endif %}
{% endblock %}

templates/splash/actions/services/thank_you.html
{% extends 'splash/forms/base.html' %}
{% load staticfiles %}

{% block body_content %}
    <center><h2><label>Kiitos!</label></h2></center>
    <p>Palvelun tiedot siirtyvät Palveluviuhkan verkkosivuille, kun ylläpitäjä on tarkistanut ja hyväksynyt tiedot.</p>
    <p>Muistathan jatkossa käydä Palveluviuhkan verkkosivuilla päivittämässä palvelun tietoja, jos palvelussa tapahtuu
        muutoksia. Muista myös päivittää verkko-osoitteiden linkit, jos ne muuttuvat.</p>
    <p>Mikäli myöhemmin haluat poistaa palvelun tiedot kokonaan Palveluviuhkan verkkosivuilta, lähetä asiasta
        sähköpostitse viesti suoraan ylläpitäjälle osoitteella viuhka@turku.fi</p>
    <br>
<form method="get" action="/form/">
    <button type="submit" class="btn button-info">Lisää uusi palvelu</button>
</form>
{% endblock %}

templates/splash/actions/services/view.html
{% extends 'splash/forms/base.html' %}
{{ super() }}

{% block body_content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="container">
    <div class="row">
        <a class="btn btn-primary btn-lg" href="javascript:history.back()" role="button"
            style="background: #00A97A;border-color: #00A97A;">
            <i class="fa fa-caret-left"></i>
            <i class="fa fa-caret-left"></i>
            <i class="fa fa-caret-left"></i>
            &nbsp; Palaa hakuun
        </a>
    </div>
    <div class="row">
        <div class="col">
            <div class="row">
                <h1> {{ service.name }} </h1>
            </div>
            {% if service.organization %}
            <div class="row">
                <div class="col">
                    <div class="row">
                        <h2> Palvelun toteuttaja </h2>
                    </div>
                    <div class="row">
                        <p> {{ service.organization }} </p>
                    </div>
                </div>
            </div>
            {% endif %}
            {% if service.ingress %}
            <div class="row">
                <div class="col">
                    <div class="row">
                        <h2> Tiivistelmä </h2>
                    </div>
                    <div class="row">
                        <p> {{ service.ingress }} </p>
                    </div>
                </div>
            </div>
            {% endif %}
            {% if service.description %}
            <div class="row">
                <div class="col">
                    <div class="row">
                        <h2> Palvelun kuvaus </h2>
                    </div>
                    <p> {{ service.description | safe }} </p>
                </div>
            </div>
            {% endif %}
            {% if service.constraint %}
            <div class="row">
                <div class="col">
                    <div class="row">
                        <h2> Rajaukset </h2>
                    </div>
                    <div class="row">
                        <p> {{ service.constraint | safe }} </p>
                    </div>
                </div>
            </div>
            {% endif %}
            {% if service.description4 %}
            <div class="row">
                <div class="col">
                    <div class="row">
                        <h2> Toimi näin </h2>
                    </div>
                    <p> {{ service.description4 | safe }} </p>
                </div>
            </div>
            {% endif %}
            {% if service.address %}
            <div class="row">
                <div class="col">
                    <div class="row">
                        <h2> Käyntitiedot </h2>
                    </div>
                    <p> {{ service.address | safe }} </p>
                </div>
            </div>
            {% endif %}
            {% if service.post_address %}
            <div class="row">
                <div class="col">
                    <div class="row">
                        <h2> Postiosoite </h2>
                    </div>
                    <p> {{ service.post_address | safe }} </p>
                </div>
            </div>
            {% endif %}
            {% if service.contact_person_phone %}
            <div class="row">
                <div class="col">
                    <div class="row">
                        <h2> Puhelin </h2>
                    </div>
                    <p> {{ service.contact_person_phone | safe  }} </p>
                </div>
            </div>
            {% endif %}
            {% if service.contact_email %}
            <div class="row">
                <div class="col">
                    <div class="row">
                        <h2> Sähköposti </h2>
                    </div>
                    <p> {{ service.contact_email | safe  }} </p>
                </div>
            </div>
            {% endif %}
            <div class="row">
                <div class="col">
                    <div class="row">
                        <h2> Verkkosivut </h2>
                    </div>
                    {{ service.www | safe }}
                    {% if service.facebook %}
                    <div class="row">
                        <div class="col">
                            <div class="row">
                                <a href="{{ service.facebook }}">
                                    <i class="fa fa-facebook"></i>
                                    facebook
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if service.twitter %}
                    <div class="row">
                        <div class="col">
                            <div class="row">
                                <a href="{{ service.twitter }}">
                                    <i class="fa fa-twitter"></i>
                                    {{ service.twitter }}
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}